objects/Connection_Behavior__c.object
<CustomObject>
    <description>Defines the deployment, back-promotion, and quality gate behavior for connections or sets the default for connections into a particular environment.</description>
    <fields>
        <fullName>Back_Promotion_Behavior__c</fullName>
        <description>How should user stories be moved back from higher environments (prod/test) to lower environments (test/dev)</description>
        <inlineHelpText>How should user stories be moved back from higher environments (prod/test) to lower environments (test/dev)</inlineHelpText>
        <label>Back-Promotion Execution</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automated</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promotion_Behavior__c</fullName>
        <description>How should user stories be deployed from lower (dev/test) environments to higher environments (test/prod)</description>
        <inlineHelpText>How should user stories be deployed from lower (dev/test) environments to higher environments (test/prod)</inlineHelpText>
        <label>Promotion Execution</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Connection_Behavior_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promotion_Schedule__c</fullName>
        <description>The schedule for deployments (if they are scheduled)</description>
        <inlineHelpText>The schedule for deployments (if they are scheduled)</inlineHelpText>
        <label>Promotion Schedule</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Connection Behavior</label>
    <nameField>
        <label>Connection Behavior Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Behaviors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ConnectionBehaviorTriggerHandler.cls
/**
 * Created by COPADO\ucan on 9/6/19.
 */

@IsTest
private class Test_ConnectionBehaviorTriggerHandler {
    @IsTest
    static void testBehavior() {
        Test.startTest();
        Connection_Behavior__c cbItem = CMTestMethodUtilities.createConnectionBehavior('Automated', '57 0 1 ? * * *');
        System.debug('cbItem 1 '+cbItem);
        cbItem.Promotion_Behavior__c = 'Scheduled';
        update cbItem;
        System.debug('cbItem==2=> '+cbItem);
        List<CronTrigger> ctList = [SELECT Id, CronExpression, CronJobDetailId, OwnerId, State FROM CronTrigger WHERE CronExpression = '57 0 1 ? * * *'];
        System.debug('ctList==1==> ' + ctList);
        System.assertEquals(1, ctList.size());
        cbItem.Back_Promotion_Behavior__c = 'Scheduled';
        update cbItem;
        ctList = [SELECT Id, CronExpression, CronJobDetailId, OwnerId, State FROM CronTrigger WHERE CronExpression = '57 0 1 ? * * *'];
        System.debug('ctList==2==> ' + ctList);
        System.assertEquals(2, ctList.size());

        cbItem.Promotion_Schedule__c = '19 1 2 ? * * *';
        update cbItem;
        ctList = [SELECT Id, CronExpression, CronJobDetailId, OwnerId, State FROM CronTrigger WHERE CronExpression = '19 1 2 ? * * *'];
        System.debug('ctList==3==> ' + ctList);
        System.assertEquals(1, ctList.size());

        cbItem.Back_Promotion_Behavior__c = 'Manual';
        cbItem.Promotion_Behavior__c = 'Automated';
        update cbItem;
        delete cbItem;

        Test.stopTest();

    }
}