objects/Deployment_Job__c.object
<CustomObject>
    <fields>
        <fullName>Last_Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Latest result with more details of the job execution.</inlineHelpText>
        <label>Last Result</label>
        <referenceTo>Result__c</referenceTo>
        <relationshipLabel>Deployment Jobs</relationshipLabel>
        <relationshipName>Deployment_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Deployment Jobs</relationshipLabel>
        <relationshipName>Deployment_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Result__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>Current status of the result. Confirms if the result is pending or completed.</description>
        <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ResultTriggerHelper.cls
public with sharing class ResultTriggerHelper {
    private static Map<Id, String> statusByResultIds { get; set; }
    public ResultTriggerHelper() {
    }

    public static void prepareData(List<SObject> records) {
        statusByResultIds = new Map<Id, String>();
        for (SObject so : records) {
            Result__c resultRecord = (Result__c) so;
            if (resultRecord.Status__c == 'Success' || resultRecord.Status__c == 'Failed') {
                statusByResultIds.put(resultRecord.Id, resultRecord.Status__c);
            }
        }
    }

    public static void updateDeploymentJobStatus() {
        List<Deployment_Job__c> deploymentJobs = new List<Deployment_Job__c>(
            [
                SELECT Id, Step__c, Status__c, Last_Result__c
                FROM Deployment_Job__c
                WHERE Last_Result__c IN :statusByResultIds.keyset()
                WITH SECURITY_ENFORCED
            ]
        );

        if (!deploymentJobs.isEmpty()) {
            for (Deployment_Job__c deploymentJob : deploymentJobs) {
                deploymentJob.Status__c = statusByResultIds.get(deploymentJob.Last_Result__c);
            }

            Utilities.Secure_DML(deploymentJobs, Utilities.DML_Action.UPD, Schema.Sobjecttype.Deployment_Job__c);
        }
    }
}