objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The selected Project should be linked to an active Deployment Flow</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MetaData</fullName>
                    <default>true</default>
                    <label>MetaData</label>
                </value>
                <value>
                    <fullName>Full Profiles</fullName>
                </value>
                <value>
                    <fullName>Full Permission Sets</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Translations</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Bulk Data</fullName>
                </value>
                <value>
                    <fullName>Data Template</fullName>
                </value>
                <value>
                    <fullName>Delete MetaData</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Git MetaData</fullName>
                </value>
                <value>
                    <fullName>URL Callout</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDeploymentWizardFailures.cls
/**
 * Created by fede on 27/12/2017.
 */

@IsTest
private class TestDeploymentWizardFailures {
    @testSetup
    static void setupData() {
        TestUtilities.enableLicenses(1, 1, 0);
    }
    static void setupDataDML() {
        TestUtilities.insertUser('user1-TestDeploymentWizard@test-copado.org','System Administrator');
        TestUtilities.assignLicense('user1-TestDeploymentWizard@test-copado.org', false, true, false);
        TestUtilities.assignLicense(UserInfo.getUserName(), true, false, false);
        testMethodUtilities.upsertOrgwideSettings();
    }
    static testMethod void testPromotionDeploymentCCMUser_failure_messages(){
        setupDataDML();
        Feature__c f = new Feature__c(Name='Branch Management', Enabled__c=true, Quantity__c=10);
        insert f;

        Git_Repository__c g = new Git_Repository__c(name = 'g');
        insert g;
        Deployment_Flow__c flow = CMTestMethodUtilities.createFlow('simple flow');
        insert flow;
        Deployment_Flow__c flowActive = CMTestMethodUtilities.createCCMFlow('active flow', true);
        insert flowActive;

        Environment__c env1 = new Environment__c(Name='Dev1 Environment',Type__c='Sandbox');
        insert env1;
        Environment__c env2 = new Environment__c(Name='Integration Environment',Type__c='Production');
        insert env2;

        Org__c testOrg1 = CMTestMethodUtilities.createOrg('MyOrg1', 'Sandbox', 'SFDC_OrgId', null, null, system.now(), env1.Id);
        insert testOrg1;
        Org__c testOrg2 = CMTestMethodUtilities.createOrg('MyOrg2', 'Production', 'SFDC_OrgId2', null, null, system.now(), env2.Id);
        insert testOrg2;

        Deployment_Flow_Step__c dfs = CMTestMethodUtilities.createFlowStep(env1.Id, env2.Id, flow.Id);
        insert dfs;
        Deployment_Flow_Step__c dfs2 = CMTestMethodUtilities.createFlowStep(env1.Id, env2.Id, flowActive.Id);
        insert dfs2;

        Project__c testProject = CMTestMethodUtilities.createProject('test project');
        testProject.Deployment_Flow__c = flowActive.Id;
        insert testProject;
        Promotion__c testPromotion = CMTestMethodUtilities.createPromotion(testProject.Id, env1.Id);
        insert testPromotion;

        Test.startTest();
        Deployment__c testDeployment = testMethodUtilities.create('a',System.now(), System.now(),testOrg1.Id,'c','d');
        insert testDeployment;
        System.assert([select Id from deployment__c where Id = :testDeployment.Id].size() == 1);
        Deployment__c testDeploymentWithPromotion = testMethodUtilities.create('a',System.now(), System.now(),testOrg1.Id,'c','d');
        testDeploymentWithPromotion.Promotion__c = testPromotion.Id;
        insert testDeploymentWithPromotion;

        Step__c testStep1 = testMethodUtilities.create('Apex','b','{"testLevel":"NoTestRun","replacements":[]}',testDeployment.Id,1,'Draft','Apex');
        insert testStep1;
        Step__c testStep2 = testMethodUtilities.create('Apex','b','{"testLevel":"NoTestRun","replacements":[]}',testDeploymentWithPromotion.Id,1,'Draft','Apex');
        insert testStep2;
        Destination_Org__c testDestOrg = testMethodUtilities.create(testDeployment.Id,'Draft',testOrg2.Id);
        insert testDestOrg;
        Destination_Org__c testDestOrg2 = testMethodUtilities.create(testDeploymentWithPromotion.Id,'Draft',testOrg2.Id);
        insert testDestOrg2;

        // Run test as a CCM User
        User user = [SELECT Id FROM User WHERE Username ='user1-TestDeploymentWizard@test-copado.org'];

        System.runAs(user) {
            PageReference pref = Page.DeploymentWizard;
            pref.getParameters().put('id',testDeployment.id);
            pref.getParameters().put('gotoStep','deployNow');
            Test.setCurrentPage(pref);

            DeploymentWizardExtension ext = new DeploymentWizardExtension(new ApexPages.StandardController(testDeployment));
            System.assert(testMethodUtilities.hasMessage(Label.COPADO_DEPLOYER_LICENSE_NOT_ENABLED));

            PageReference pref2 = Page.DeploymentWizard;
            pref2.getParameters().put('id',testDeploymentWithPromotion.id);
            pref2.getParameters().put('gotoStep','deployNow');
            Test.setCurrentPage(pref2);

            DeploymentWizardExtension ext2 = new DeploymentWizardExtension(new ApexPages.StandardController(testDeploymentWithPromotion));
            System.assert(testMethodUtilities.hasMessage(Label.CCM_DESTINATION_ORG_INVALID));

            env2.Type__c = 'Sandbox';
            update env2;
            testOrg2.Org_Type__c = 'Sandbox';
            update testOrg2;

            DeploymentWizardExtension ext3 = new DeploymentWizardExtension(new ApexPages.StandardController(testDeploymentWithPromotion));
            System.assert(testMethodUtilities.hasMessage(Label.CBM_FLOW_INVALID));

            testProject.Deployment_Flow__c = flow.Id;
            update testProject;

            DeploymentWizardExtension ext4 = new DeploymentWizardExtension(new ApexPages.StandardController(testDeploymentWithPromotion));
            System.assert(testMethodUtilities.hasMessage(Label.PROMOTION_FLOW_INACTIVE));
        }
        Test.stopTest();
    }
    static testMethod void testGotoDeployNowPage_failure_messages(){
        setupDataDML();
        Org__c testFromOrg = testMethodUtilities.createOrg('a','b','c','d','e', System.now());
        insert testFromOrg;
        Deployment__c testDeployment = testMethodUtilities.create('a',System.now(), System.now(),testFromOrg.Id,'c','d');
        insert testDeployment;
        System.assert([select Id from deployment__c where Id = :testDeployment.Id].size() == 1);
        PageReference pref = Page.DeploymentWizard;
        pref.getParameters().put('id',testDeployment.id);
        pref.getParameters().put('gotoStep','deployNow');
        Test.setCurrentPage(pref);

        test.startTest();
        DeploymentWizardExtension ext = new DeploymentWizardExtension(new ApexPages.StandardController(testDeployment));
        test.stopTest();
        System.debug('ApexPages messages: '+ApexPages.getMessages());
        System.assertEquals(false, ext.step_setupSchedule);
        System.assert(testMethodUtilities.hasMessage(Label.MISSING_DEST_ORGS_MESSAGE));
        System.assert(testMethodUtilities.hasMessage(Label.MISSING_STEPS_MESSAGE));
    }
}