objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Deployed__c</fullName>
        <formula>IF(Deployment_Jobs_Count__c &gt; 0,
SUM_Deployed__c / Deployment_Jobs_Count__c,
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Deployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Deployment_Job__c.object
<CustomObject>
    <fields>
        <fullName>Deployed__c</fullName>
        <label>% Deployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Destination_Org__c</fullName>
        <label>Destination Org</label>
        <referenceTo>Destination_Org__c</referenceTo>
        <relationshipLabel>Deployment Jobs</relationshipLabel>
        <relationshipName>Deployment_Jobs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status_Flag__c</fullName>
        <formula>IMAGE(
				
  CASE(Status__c,  
  &quot;Success&quot;, &quot;/img/samples/flag_green.gif&quot;,
  &quot;Failed&quot;, &quot;/img/samples/flag_red.gif&quot;,
  &quot;In progress&quot;, &quot;/img/loading.gif&quot;,
  &quot;/s.gif&quot;), 
   &quot;&quot; )+&quot; &quot;+   
			IMAGE(
							CASE(External_Status__c,
			         &quot;Queued&quot;, &quot;/img/loading.gif&quot;,
            &quot;Success&quot;,&quot;/img/samples/flag_green.gif&quot;,
            &quot;Timed out&quot;, &quot;/img/samples/flag_red.gif&quot;,
            &quot;Failed&quot;,&quot;/img/samples/flag_red.gif&quot;,
												&quot;/s.gif&quot;
							), &quot;&quot;
			)</formula>
        <label>Status Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Deployment Jobs</relationshipLabel>
        <relationshipName>Deployment_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Org_Name__c</fullName>
        <formula>Destination_Org__r.To_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>To Org Name</label>
        <type>Text</type>
    </fields>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployed__c</fullName>
        <formula>IF(Org_Count__c &gt; 0,
SUM_Deployed__c / Org_Count__c,
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Deployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status_Flag__c</fullName>
        <formula>IMAGE( 
  CASE(  Status__c,  &quot;Completed Successfully&quot;, &quot;/img/samples/flag_green.gif&quot;,
  &quot;In progress&quot;, &quot;/img/loading.gif&quot;, 
  &quot;Completed with Errors&quot;, &quot;/img/samples/flag_red.gif&quot;, 
  &quot;/s.gif&quot;), 
   &quot;&quot; )</formula>
        <label>Status Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MetaData</fullName>
                    <default>true</default>
                    <label>MetaData</label>
                </value>
                <value>
                    <fullName>Full Profiles</fullName>
                </value>
                <value>
                    <fullName>Full Permission Sets</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Translations</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Bulk Data</fullName>
                </value>
                <value>
                    <fullName>Data Template</fullName>
                </value>
                <value>
                    <fullName>Delete MetaData</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Git MetaData</fullName>
                </value>
                <value>
                    <fullName>URL Callout</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dataJson__c</fullName>
        <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
        <label>dataJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ViewDeploymentExtension.cls
public with sharing class ViewDeploymentExtension {
    public ApexPages.StandardController stdController {get; set;}
    public Deployment__c deployment {get;set;}
    
    public List<Step__c> steps {get;set;}   
    public List<Destination_Org__c> destinationOrgs {get;set;}
    public List<matrixWrapper> matrix {get;set;}
    public Map<String, Deployment_Job__c> mapDeploymentJobsString {get;set;}
    
    // STEPS
    public ID selectedStep {get;set;}
    public Step__c step {get; set;}
    public ApexPages.StandardController stepController {get; set;}
    public Map<Id, Step__c> mapSteps {get;set;}
    public String dataStepQuery {get;set;}
    public String dataStepObject {get;set;}
    public String dataStepExternalId {get;set;}
    
    // ERRORS
    public boolean runPoller {get;set;}
    public Map<String, boolean> mapAttachments {get;set;}
    
    public class matrixWrapper{
        public Step__c step {get;set;}
        public List<Deployment_Job__c> jobs {get;set;}
        public matrixWrapper(Step__c s, List<Deployment_Job__c> js){
            this.step = s;
            this.jobs = js;
        }
    }
    public ViewDeploymentExtension(ApexPages.StandardController stdController) {
        deployment = (Deployment__c)stdController.getRecord();
        if(deployment==null)deployment=new Deployment__c();
        buildMatrix();

    }
    public void getStepDetail(){
        step = new Step__c();
        step = Utilities.getStepById(selectedStep);
        dataStepQuery = '';
        dataStepObject = '';
        dataStepExternalId = '';
        if(step.type__c=='Data'||step.type__c=='Bulk Data'){
            Map<String, Object> fullMap = (Map<String, Object>)JSON.deserializeUntyped(step.datajson__c);
            dataStepQuery = (String)fullMap.get('q');
            dataStepObject = (String)fullMap.get('o');
            dataStepExternalId = (String)fullMap.get('f');
        }
    }
    public PageReference buildMatrix(){
        runPoller = false;
        deployment = Utilities.getDeploymentById(EncodingUtil.urlEncode(ApexPages.currentPage().getParameters().get('id'),'UTF-8'));
        if(deployment.status__c=='In progress'||deployment.status__c=='Scheduled'){
            runPoller = true;
        }
        steps = new List<Step__c>();
        step = new Step__c();
        stepController = new ApexPages.StandardController(step);
        destinationOrgs = new List<Destination_Org__c>();
        matrix = new List<matrixWrapper>();
        mapDeploymentJobsString = new Map<String, Deployment_Job__c>();
        mapSteps = new Map<Id, Step__c>();
        
        steps = Utilities.getStepsByDeploymentId(deployment.Id);
        for(Step__c s : steps){ 
            mapSteps.put(s.id, s); 
            if(selectedStep == s.id){
                step = s;
            }
        }
        destinationOrgs = Utilities.getDestinationOrgsByDeploymentId(deployment.Id);
        
        List<Deployment_Job__c> deploymentJobs = new List<Deployment_Job__c>();
        if(Schema.sObjectType.Deployment_Job__c.isQueryable() && Schema.sObjectType.Deployment_Job__c.isAccessible()) deploymentJobs = [SELECT Id, Name, Deployed__c, Destination_Org__c, External_Id__c, Status__c, Status_Flag__c, Step__c, To_Org_Name__c FROM Deployment_Job__c WHERE Step__r.deployment__c = :EncodingUtil.urlEncode(deployment.Id,'UTF-8') LIMIT 10000];
        Set<Id> completedJobs = new Set<Id>();
        mapAttachments = new Map<String, boolean>();
        //Set<Id> parentIdSet = new Set<Id>();
        for(Deployment_Job__c d : deploymentJobs){
            mapDeploymentJobsString.put(d.step__c+''+d.destination_org__c, d);
            if(d.status__c=='Failed')completedJobs.add(d.Id);
            //parentIdSet.add(d.Id);
            mapAttachments.put(d.Id+'.json', false);
        }
        //if(deployment.status__c == 'Completed with Errors'){
           // parentIdSet.add(deployment.Id);
        //}
        mapAttachments.put(deployment.Id+'.json', false);
        List<Attachment> attachments = [SELECT Id, ParentId, Name, Body FROM Attachment WHERE
            //ParentId in :parentIdSet and 
            ParentId = :EncodingUtil.urlEncode(deployment.Id,'UTF-8') and
            Name LIKE '%.json' AND (NOT(Name LIKE 'OLD_%')) LIMIT 10000];
        Attachment deploymentErrorAttachment = null;
        for(Attachment a : attachments){
            if(a.name==deployment.Id+'.json'){
                deploymentErrorAttachment = a;
            }
            mapAttachments.put(a.name, true);
        }
        if(deploymentErrorAttachment != null){
            //system.debug('#### deployment error attachement body: '+deploymentErrorAttachment.body.tostring());
            List<errorWrapper> errorList = new List<errorWrapper>();
            errorList = (List<errorWrapper>)JSON.deserialize(deploymentErrorAttachment.body.tostring(), List<errorWrapper>.class);
            //system.debug('#### errorList.size(): '+errorList.size());
            for(errorWrapper er : errorList){
                //system.debug('#### er.m: '+er.m);
                if(er.l=='ERROR')ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, er.m));
                else if(er.l=='INFO')ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, er.m));
                else if(er.l=='WARNING')ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, er.m));
                else if(er.l=='CONFIRM')ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, er.m));
                else ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, er.m));
            }               
        }
        Integer rowCount = 0;
        for(Step__c s : steps){
            List<Deployment_Job__c> tmpList = new List<Deployment_Job__c>();
            for(Deployment_Job__c d : deploymentJobs){
                if(d.step__c == s.id)tmpList.add(d);
            }
            matrix.add(new matrixWrapper(s, tmpList));
        }
        return null;
    }
    public class errorWrapper{
        public string l{get;set;}
        public string m{get;set;}
        public string t{get;set;}
        public errorWrapper(String sl, String sm, String st){
            this.l = sl;
            this.m = sm;
            this.t = st;
        }
    }   
}