objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestViewDeploymentExtension.cls
@isTest
private class TestViewDeploymentExtension {
	@testSetup static void setupTestData(){
		TestUtilities.setTestSettingsEE();
	}
	@testSetup static void setupTestDataDML(){
		testMethodUtilities.upsertOrgwideSettings();
	}
    static testMethod void myUnitTest() {
		Org__c testFromOrg = testMethodUtilities.createOrg('OrgName','Production','SFDC_OrgId','SFDC_TOKEN','USERNAME', System.now());
		insert testFromOrg;
		Deployment__c testDeployment = testMethodUtilities.create('DEPLOYMENT_NAME',System.now(), System.now(),testFromOrg.Id,'Deploy now','Scheduled');
		insert testDeployment;
		Step__c testStep = testMethodUtilities.create('Step 1','attId','JSONString',testDeployment.Id,0,'Not started','MetaData');
		insert testStep;
		Destination_Org__c testDestOrg = testMethodUtilities.create(testDeployment.Id,'Draft',testFromOrg.Id);
        insert testDestOrg;
        
		
		PageReference pref = Page.DeploymentWizard;
		pref.getParameters().put('id',testDeployment.id);
		Test.setCurrentPage(pref);		

		ViewDeploymentExtension ext = new ViewDeploymentExtension(new ApexPages.StandardController(testDeployment));
		system.assertEquals(true, ext.runPoller);
		system.assertEquals(1, ext.mapDeploymentJobsString.size());
		system.debug('## keys: '+ext.mapAttachments.keySet());
		system.debug('## values: '+ext.mapAttachments.values());
		system.assertEquals(2, ext.mapAttachments.size());
		system.assertEquals(1, ext.matrix.size());
		system.assertEquals(testStep.Id, ext.matrix[0].step.Id);
		system.assertEquals(1, ext.matrix[0].jobs.size());
		
		Attachment depErrors = new Attachment(Body=Blob.valueOf('[{"l":"ERROR","m":"This is a deployment error message","t":""}]'),Name=testDeployment.Id+'.json',ParentId=testDeployment.Id);
		insert depErrors;
		Attachment jobError = new Attachment(Body=Blob.valueOf('[{"l":"INFO","m":"Deployment job message","t":""}]'),Name=ext.matrix[0].jobs[0].Id+'.json',ParentId=testDeployment.Id);
		insert jobError;
		testDeployment.status__c = 'Completed Successfully';
		update testDeployment;
		ext = new ViewDeploymentExtension(new ApexPages.StandardController(testDeployment));
		system.assertEquals(false, ext.runPoller);
		for(String i : ext.mapAttachments.keySet()){
			system.assertEquals(true, ext.mapAttachments.get(i));
		}
		system.assert(testMethodUtilities.hasMessage('This is a deployment error message'));
		
		ext.selectedStep = testStep.Id;
		ext.getStepDetail();
		
		DeployAPI.cancelDeployment(ext.deployment.Id);
    }
}