objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only Active Templates are available when searching for them, for example in deployment steps</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <formula>IF(Deployment_Jobs_Count__c&gt;0,
Count_Completed__c /  Deployment_Jobs_Count__c,
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Count_Completed__c</fullName>
        <label># Completed</label>
        <summarizedField>Step__c.Count_Completed__c</summarizedField>
        <summaryForeignKey>Step__c.Deployment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Deployed__c</fullName>
        <formula>IF(Deployment_Jobs_Count__c &gt; 0,
SUM_Deployed__c / Deployment_Jobs_Count__c,
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Deployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SUM_Deployed__c</fullName>
        <label>SUM Deployed</label>
        <summarizedField>Step__c.SUM_Deployed__c</summarizedField>
        <summaryForeignKey>Step__c.Deployment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Automated_Behaviour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automation that originated this deployment step.</description>
        <inlineHelpText>Automation that originated this deployment step.</inlineHelpText>
        <label>Automated Behaviour</label>
        <referenceTo>Quality_Gate__c</referenceTo>
        <relationshipLabel>Execution History</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This only Apply for Metadata Steps. None of the other Steps types are affected by this checkbox. 
WARNING: Credits consumption will apply as a regular deployment since resource-wise is exactly the same as a real deployment.</inlineHelpText>
        <label>CheckOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commit_Name__c</fullName>
        <label>Commit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <formula>IF(Org_Count__c &gt; 0, 
Count_Completed__c / Org_Count__c,
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Count_Completed__c</fullName>
        <label># Completed</label>
        <summaryFilterItems>
            <field>Deployment_Job__c.Status__c</field>
            <operation>equals</operation>
            <value>Success, Failed</value>
        </summaryFilterItems>
        <summaryForeignKey>Deployment_Job__c.Step__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Deployed__c</fullName>
        <formula>IF(Org_Count__c &gt; 0,
SUM_Deployed__c / Org_Count__c,
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Deployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Task_Notified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent sending multiple notifications to the same Manual Task owner per Task</description>
        <label>Manual Task Notified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_Task_Owner__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <label>Notify Task Owner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Notify_Task_Owner_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Org_Count__c</fullName>
        <label>Org Count</label>
        <summaryForeignKey>Deployment_Job__c.Step__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Run_all_tests__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run all tests</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SUM_Deployed__c</fullName>
        <label>SUM Deployed</label>
        <summarizedField>Deployment_Job__c.Deployed__c</summarizedField>
        <summaryForeignKey>Deployment_Job__c.Step__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status_Flag__c</fullName>
        <formula>IMAGE( 
  CASE(  Status__c,  &quot;Completed Successfully&quot;, &quot;/img/samples/flag_green.gif&quot;,
  &quot;In progress&quot;, &quot;/img/loading.gif&quot;, 
  &quot;Completed with Errors&quot;, &quot;/img/samples/flag_red.gif&quot;, 
  &quot;/s.gif&quot;), 
   &quot;&quot; )</formula>
        <label>Status Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MetaData</fullName>
                    <default>true</default>
                    <label>MetaData</label>
                </value>
                <value>
                    <fullName>Full Profiles</fullName>
                </value>
                <value>
                    <fullName>Full Permission Sets</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Translations</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Bulk Data</fullName>
                </value>
                <value>
                    <fullName>Data Template</fullName>
                </value>
                <value>
                    <fullName>Delete MetaData</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Git MetaData</fullName>
                </value>
                <value>
                    <fullName>URL Callout</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Attachment__c</fullName>
        <formula>IF( 
  NOT(ISBLANK(Attachment_Id__c)),
  HYPERLINK(&quot;/&quot;+Attachment_Id__c, &quot;View&quot;, &quot;_blank&quot;),
  &quot;&quot;
)</formula>
        <label>View Attachment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dataJson__c</fullName>
        <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
        <label>dataJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AutomationTemplateExportImportHelper.cls
public with sharing class AutomationTemplateExportImportHelper {
    public static Id exportAutomationAndReturnContentDocumentId(Id automationTemplateId, String automationTemplateName) {
        Id createdFileId = null;
        try {
            List<Deployment__c> deployments = returnAutomationWithSteps(automationTemplateId);
            if (!deployments.isEmpty()) {
                createdFileId = insertFileToAutomationTemplateAndReturnContentDocumentId(
                    automationTemplateId,
                    automationTemplateName,
                    JSON.serializePretty(deployments[0])
                );
            }
        } catch (Exception ex) {
            System.debug('error : ' + ex.getMessage());
        }
        return createdFileId;
    }

    private static List<Deployment__c> returnAutomationWithSteps(Id automationId) {
        List<Deployment__c> deployments = [
            SELECT
                Name,
                Description__c,
                Active__c,
                (
                    SELECT
                        Automated_Behaviour__c,
                        Deployment__c,
                        Name,
                        Read_Only__c,
                        Notify_Task_Owner__c,
                        Manual_Task_Notified__c,
                        SUM_Deployed__c,
                        Org_Count__c,
                        Count_Completed__c,
                        Type__c,
                        dataJson__c,
                        Status__c,
                        View_Attachment__c,
                        Status_Flag__c,
                        Run_all_tests__c,
                        Order__c,
                        Git_Repository__c,
                        Deployed__c,
                        Completed__c,
                        Commit_Name__c,
                        Commit_Id__c,
                        Branch__c,
                        CheckOnly__c
                    FROM Steps__r
                )
            FROM Deployment__c
            WHERE Id = :automationId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        return deployments;
    }

    private static Id insertFileToAutomationTemplateAndReturnContentDocumentId(
        Id automationTemplateId,
        String automationTemplateName,
        String fileContent
    ) {
        String contentName = String.isNotBlank(automationTemplateName) ? automationTemplateName : automationTemplateId;
        ContentVersion contentVersionRecord = new ContentVersion();
        contentVersionRecord.ContentLocation = 'S';
        contentVersionRecord.PathOnClient = contentName + '.json';
        contentVersionRecord.Title = contentName;
        contentVersionRecord.VersionData = Blob.valueOf(fileContent);
        insert contentVersionRecord;

        Id contentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionRecord.Id].ContentDocumentId;
        ContentDocumentLink contentDocumentRecordLink = new ContentDocumentLink();
        contentDocumentRecordLink.LinkedEntityId = automationTemplateId;
        contentDocumentRecordLink.ContentDocumentId = contentDocumentId;
        contentDocumentRecordLink.shareType = 'V';
        insert contentDocumentRecordLink;

        return contentDocumentId;
    }
}