objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Test_Frequency__c</fullName>
        <description>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</description>
        <inlineHelpText>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</inlineHelpText>
        <label>Test Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OrgTriggerHelper.cls
public without sharing class OrgTriggerHelper {
	private static boolean sched = false;
	private static String[] idsToRemoveAttach = new String[]{};
    private static Map<String, Environment__c> environmentMap;
	public static List<Environment__c> environments;

    public static void prepareData(List<SObject> records){
        environments = new List<Environment__c>();
        environmentMap = new Map<String, Environment__c>();
        Set<String> orgIds = new Set<String>();
        // NR: unneeded. Java oauth part will handle clashing.
        //Map<String,Integer> unique_ids = new Map<String,Integer>();
        
        for(SObject so : records){
            Org__c o = (Org__c)so;
            String tmp = extractOrgId((String)o.SFDC_Org_ID__c);
            if(tmp!=null)orgIds.add(tmp);
            // prevent unique sfdc org id field to clash when adding multiple org credentials for the same org
            // NR: unneeded. Java oauth part will handle clashing.
            //if(isValidCopadoSFDC_Org_Id(o.SFDC_Org_ID__c))unique_ids.put(getBaseSFDC_Org_Id(o.SFDC_Org_ID__c),0);
        }
        Set<Id> eids = new Set<Id>();
        for(Environment__c e : [select Id, Name, Org_ID__c from Environment__c where Org_ID__c IN :orgIds]){
            environmentMap.put(e.Org_ID__c, e);
            eids.add(e.Id);
        }
        for(SObject so : records){
            Org__c neworg = (Org__c)so;
            String sfdcorgId = extractOrgId((String)neworg.SFDC_Org_ID__c);
			Environment__c e = environmentMap.get(sfdcorgId);
            if(!environmentMap.containsKey(sfdcorgId)){

                e = new Environment__c();
                e.Name = neworg.Name;
                e.Type__c = neworg.Org_Type__c;
                e.Org_ID__c = sfdcorgId;
                environments.add(e);
            }        
        }
        Utilities.Secure_DML(environments, Utilities.DML_Action.UPS, schema.Sobjecttype.Environment__c);
        
        for(Environment__c e : [select Id, Name, Org_ID__c from Environment__c where Org_ID__c IN :orgIds]){
            environmentMap.put(e.Org_ID__c, e);
            eids.add(e.Id);
        }
        
        /* NR: unneeded. Java oauth part will handle clashing.

        //query if exist already a clashing org credential
        if(Trigger.new !=null) {
            for(Org__c o:[select Id, SFDC_Org_ID__c from Org__c where SFDC_Org_ID__c!='' and (not (id in :Trigger.newMap.keyset()))]){
                if( isValidCopadoSFDC_Org_Id(o.SFDC_Org_ID__c) && unique_ids.containsKey(getBaseSFDC_Org_Id(o.SFDC_Org_ID__c))){
                    Integer current = unique_ids.get(getBaseSFDC_Org_Id(o.SFDC_Org_ID__c));
                    unique_ids.put(getBaseSFDC_Org_Id(o.SFDC_Org_ID__c), current+1);   
                }
            }
            //set the SFDC_Org_Id with an un-clashing one
            for(SObject so:Trigger.new){
                Org__c o = (Org__c)so;
                //this will only add a copy number when there is a clash and it doen't have a copy number already. 
                if(isValidCopadoSFDC_Org_Id(o.SFDC_Org_ID__c) && unique_ids.get(o.SFDC_Org_ID__c)>0){
                    o.SFDC_Org_ID__c += '_'+ unique_ids.get(o.SFDC_Org_ID__c);
                }
            }
        }
		*/
    }
	public static Boolean isScheduled(Org__c o){
		if(o.Test_Frequency__c!=null && o.Test_Frequency__c!='None' && o.Validated_Date__c!=null){
			sched = true;
			return true;
		}
		return false;
	}
	public static void checkApexTest(Org__c o){
		if(isScheduled(o) && !FeatureHelper.isFeatureEnabled('Apex Test')){
			o.Test_Frequency__c = 'None';
		}
	}
	public static void enforceScheduler(){
		if(sched)BatchHelper.enforceScheduler();
	}
	public static void isMetadataChanged(Org__c o, Org__c old){
		if(old.Metadata_Types__c != o.Metadata_Types__c){
			idsToRemoveAttach.add(o.id);
		}
	}
	public static void deleteMetadataAttachments(){
        Utilities.Secure_DML([SELECT Id FROM Attachment where ParentId = :idsToRemoveAttach and Name ='MetaData'], Utilities.DML_Action.DEL, schema.Sobjecttype.Attachment);
	}
    public static void setOrgEnvironment(Org__c neworg){
        String newId = extractOrgId(neworg.SFDC_Org_ID__c);
        //boolean isValidated = (neworg.Validated_Date__c!=null)?true:false;
        System.debug('**** set org environament for SFDC_Org_ID__c: ' + neworg.SFDC_Org_ID__c);
        System.debug('**** set org environament for newId: ' + newId);
        System.debug('**** env map: ' + environmentMap);
        if(newId != null){
            neworg.environment__c = environmentMap.get(newId).Id;
        }
    }
    private static String extractOrgId(String s){
        if(s==null)return null;
        if(s.length() >= 37 && s.contains('_'))return s.split('_')[0];
        if(s.length() == 18 && s.startsWith('00D'))return s;
        return null;
    }
    private static boolean isValidCopadoSFDC_Org_Id(String oid){
        return String.isNotBlank(oid) && oid.length()>=37;
    }
    private static String getBaseSFDC_Org_Id(String oid){
        if(!isValidCopadoSFDC_Org_Id(oid))return oid;
        return oid.substring(0, 37);
    }
}