objects/Personal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object stores the personal settings for Copado</description>
    <fields>
        <fullName>Disable_Auto_Resolve__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disables Auto-Resolve from Online Conflict Resolution</description>
        <inlineHelpText>Disables Auto-Resolve from Online Conflict Resolution</inlineHelpText>
        <label>Disable Auto-Resolve</label>
        <type>Checkbox</type>
    </fields>
    <label>Personal Settings</label>
</CustomObject>

objects/Promoted_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promoted User Stories</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Outdated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Promotions</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ResolveConflictsController.cls
/**
 * Resolve Conflicts Controller
 * Allows users to mark conflicted files in a promotion as AUTO RESOLVED or RESOLVED
 * When marked as AUTO RESOLVED, the Copado backend will auto resolve the component.
 * When marked as RESOLVED, the Copado backend will merge the file as it was saved by the user.
 * @see ResolveConflicts.page
 * @version 1.0
 * @author David VENEGAS
 *
 */
public with sharing class ResolveConflictsController {
    public String preDefinedAttSource { get; set; }
    public String preDefinedAttTarget { get; set; }
    public Promotion__c promotion { get; set; }
    public List<Attachment> attachments = new List<Attachment>();
    public Attachment attachmentToResolve { get; set; }
    public Boolean goToPromotion { get; set; }
    public Boolean showHeader { get; set; }
    public Boolean disableAutoResolve {
        get {
            Personal_Settings__c settings = Personal_Settings__c.getInstance();
            return settings != null ? settings.Disable_Auto_Resolve__c : false;
        }
    }
    public String namespace { get; set; }
    public List<String> outOfPromotionMetadataAttachmentIds { get; set; }
    public String excludedMetadataAttachmentIds {
        get {
            if (String.isBlank(excludedMetadataAttachmentIds) && null != outOfPromotionMetadataAttachmentIds) {
                excludedMetadataAttachmentIds = String.join(outOfPromotionMetadataAttachmentIds, ',');
            }
            return excludedMetadataAttachmentIds;
        }
        set;
    }

    /**
     * constructor
     * @return [description]
     */
    public ResolveConflictsController() {
        attachments = new List<Attachment>();
        attachmentToResolve = null;
        goToPromotion = false;
        namespace = Settings.ns;
        outOfPromotionMetadataAttachmentIds = new List<String>();

        // Get URL promotionId parameter
        String promotionId = ApexPages.currentPage().getParameters().get('promotionId');
        if (String.isBlank(promotionId)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CONFLICT_RESOLUTION_NO_PROMOTION));
            return;
        }
        // get promotion values
        try {
            String query = 'SELECT ';
            for (Schema.FieldSetMember field : this.getHeaderFields()) {
                String fieldPath = field.getFieldPath();
                if (fieldPath != 'Name') {
                    query += fieldPath + ', ';
                }
            }
            query += ' Name FROM Promotion__c WHERE Id =:promotionId WITH SECURITY_ENFORCED LIMIT 1';
            promotion = Database.query(query);
        } catch (Exception excp) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, excp.getMessage()));
        }
    }

    public List<Schema.FieldSetMember> getHeaderFields() {
        List<Schema.FieldSetMember> fields = SObjectType.Promotion__c.FieldSets.Copado_Header_Fields.getFields();
        return fields;
    }

    /**
     *  Called by an apex:repeat in the page.
     */
    public List<Attachment> getAttachments() {
        if (promotion == null || !attachments.isEmpty()) {
            return attachments;
        }
        try {
            attachments = [
                SELECT Id, Name, ParentId
                FROM Attachment
                WHERE ParentId = :promotion.Id AND (Name LIKE 'AUTO RESOLVED%' OR Name LIKE 'RESOLVED%' OR NAME LIKE 'US-%')
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate
                LIMIT 1000
            ];
        } catch (Exception excp) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, excp.getMessage()));
        }
        promotionMetadataProcess();
        return attachments;
    }

    /*
     *  Selects an attachment from the list and saves it in the attachmentToResolve variable
     *  The attachmentToResolve variable is used by the CodeMirror text editor
     */
    public void openAttachment() {
        String attIndex = Apexpages.currentPage().getParameters().get('attIndex');
        if (attIndex != null && attachments[Integer.valueOf(attIndex)] != null) {
            attachmentToResolve = attachments[Integer.valueOf(attIndex)];
        }
    }

    /**
     * Getting user story metadatas included in the promotion record to find which attachments are related to promotion
     */
    private void promotionMetadataProcess() {
        Set<String> metadataNames = getUserStoryMetadatas();
        List<Attachment> promotionMetadataAttachments = new List<Attachment>();
        List<Attachment> outOfPromotionMetadataAttachments = new List<Attachment>();
        Set<Id> promotionMetadataAttachmentIds = new Set<Id>();
        for (String metadataItem : metadataNames) {
            String metadataName = metadataItem.substring(metadataItem.indexOf('.') + 1);
            for (Integer i = 0; i < attachments.size(); i++) {
                if (attachments[i].Name.toLowerCase().contains(metadataName.toLowerCase())) {
                    promotionMetadataAttachments.add(attachments[i]);
                    promotionMetadataAttachmentIds.add(attachments[i].Id);
                }
            }
        }

        for (Integer i = 0; i < attachments.size(); i++) {
            if (!promotionMetadataAttachmentIds.contains(attachments[i].Id)) {
                populateAttachmentName(i);
                outOfPromotionMetadataAttachments.add(attachments[i]);
                outOfPromotionMetadataAttachmentIds.add(attachments[i].Id);
            }
        }

        attachments.clear();
        if (!promotionMetadataAttachments.isEmpty()) {
            attachments.addAll(promotionMetadataAttachments);
        }

        if (!outOfPromotionMetadataAttachments.isEmpty()) {
            attachments.addAll(outOfPromotionMetadataAttachments);
        }
    }

    /**
     * Populate attachment name after resolve and auto resolve
     */
    private Attachment populateAttachmentName(Integer attachmentIndex) {
        Attachment attachmentRecord = attachments[attachmentIndex];

        if (attachmentRecord.Name.startsWith('RESOLVED')) {
            attachmentRecord.Name = attachmentRecord.Name.replace('RESOLVED', 'AUTO RESOLVED');
        } else if (!attachmentRecord.Name.startsWith('AUTO RESOLVED')) {
            attachmentRecord.Name = 'AUTO RESOLVED ' + attachmentRecord.Name;
        }
        if (!Schema.sObjectType.Attachment.fields.Name.isUpdateable() || !Schema.sObjectType.Attachment.fields.Name.isCreateable()) {
            return null;
        }
        attachments.set(attachmentIndex, attachmentRecord);
        return attachmentRecord;
    }

    /**
     * Update attachments
     */
    private void updateAttachments(List<Attachment> updatedAttachments) {
        Utilities.Secure_DML(updatedAttachments, Utilities.DML_Action.UPS, Schema.Sobjecttype.Attachment);
    }

    /**
     *  Updates the attachment name to start with "AUTO RESOLVED"
     */
    public void saveAutoResolveAttachment() {
        String attachmentIndex = Apexpages.currentPage().getParameters().get('attIndex');
        Boolean isResolved = true;

        if (attachmentIndex != null && Integer.valueOf(attachmentIndex) != null) {
            Attachment updatedAttachment = populateAttachmentName(Integer.valueOf(attachmentIndex));
            if (updatedAttachment != null) {
                updateAttachments(new List<Attachment>{ updatedAttachment });
                for (Attachment attachmentRecord : attachments) {
                    if (attachmentRecord.Name.startsWith('US-')) {
                        isResolved = false;
                        break;
                    }
                }
                if (isResolved) {
                    updatePromotionAsResolved();
                }
            }
        }
    }

    public void updatePromotionAsResolved() {
        promotion.Status__c = 'Conflicts Resolved';
        Utilities.Secure_DML(promotion, Utilities.DML_Action.UPD, schema.Sobjecttype.Promotion__c);
    }

    /**
     *  Updates the attachment name to start with "RESOLVED"
     */
    public void saveResolvedAttachment() {
        Integer index = 0;
        Boolean isResolved = true;
        if (attachmentToResolve != null) {
            for (Attachment attachmentRecord : attachments) {
                if (attachmentRecord.Id == attachmentToResolve.Id) {
                    if (attachmentRecord.Name.startsWith('AUTO RESOLVED')) {
                        attachmentRecord.Name = attachmentRecord.Name.replace('AUTO RESOLVED', 'RESOLVED');
                    } else if (!attachmentRecord.Name.startsWith('RESOLVED')) {
                        attachmentRecord.Name = 'RESOLVED ' + attachmentRecord.Name;
                    }

                    attachments.set(index, attachmentRecord); // The attachment is upserted via Javascript
                    //break;
                }
                if (attachmentRecord.Name.startsWith('US-')) {
                    isResolved = false;
                    //break; commented out to prevent attachment items to not to show up as resolved if not started to resolve with the first attachment
                }
                index = index + 1;
            }
            if (isResolved) {
                updatePromotionAsResolved();
            }
        }
    }

    /**
     *  Checks that all attachments are marked as RESOLVED or AUTO RESOLVED.
     *  If True the user is redirected to the Promotion page.
     */
    public void createDeployment() {
        List<Attachment> updatedAttachments = new List<Attachment>();
        for (Attachment attachmentRecord : attachments) {
            if (outOfPromotionMetadataAttachmentIds.contains(attachmentRecord.Id)) {
                updatedAttachments.add(attachmentRecord);
            }
            if (!attachmentRecord.Name.startsWith('RESOLVED') && !attachmentRecord.Name.startsWith('AUTO RESOLVED')) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CONFLICT_RESOLUTION_PENDING));
                return;
            }
        }
        if (!updatedAttachments.isEmpty()) {
            updateAttachments(updatedAttachments);
        }
        goToPromotion = true;
    }

    /**
     * Returns all metadata names in the promotion to check if conflicts are in the promotion or not
     */
    public Set<String> getUserStoryMetadatas() {
        Set<Id> userStoryIds = new Set<Id>();
        Set<String> userStoryMetadataAPINames = new Set<String>();
        try {
            String promotedUserStoryQuery =
                'SELECT User_Story__c FROM Promoted_User_Story__c WHERE Promotion__c = \'' +
                String.escapeSingleQuotes(promotion.Id) +
                '\' WITH SECURITY_ENFORCED';
            for (Promoted_User_Story__c promotedUSerStory : Database.query(promotedUserStoryQuery)) {
                userStoryIds.add(promotedUSerStory.User_Story__c);
            }
            if (!userStoryIds.isEmpty()) {
                String userStoryMetadataQuery = 'SELECT Id, Metadata_API_Name__c FROM User_Story_Metadata__c WHERE User_Story__c IN :userStoryIds WITH SECURITY_ENFORCED ORDER BY Last_Commit_Date__c DESC LIMIT 1000';
                for (User_Story_Metadata__c usMetadata : Database.query(userStoryMetadataQuery)) {
                    if (!userStoryMetadataAPINames.contains(usMetadata.Metadata_API_Name__c)) {
                        userStoryMetadataAPINames.add(usMetadata.Metadata_API_Name__c);
                    }
                }
            }
        } catch (Exception excp) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, excp.getMessage()));
        }
        return userStoryMetadataAPINames;
    }
}