objects/Promoted_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promoted User Stories</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status Outdated invalidates that this user story got promoted. The user story will be available again for automated promotions and back promotions if applicable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Outdated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Promotions</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The selected Project should be linked to an active Deployment Flow</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will provide the ability to deploy User Stories within a Release.</description>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Deployment_Complete_email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Deployment Complete email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The credential to the Source Environment that should be used when creating a deployment. This may be auto-populated, if left blank, based on the project&apos;s deployment flow if you are the owner of an Org Credential to the Source Environment.</inlineHelpText>
        <label>Source Org Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.Source_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Promotions (Source Org Credential)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Validation failed</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
                <value>
                    <fullName>Conflicts Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Validation_Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Most recent validation Deployment for the User Story.</description>
        <inlineHelpText>Most recent validation Deployment for the User Story.</inlineHelpText>
        <label>Last Validation Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Validation_Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Promotion containing the most recent validation Deployment.</description>
        <inlineHelpText>Promotion containing the most recent validation Deployment.</inlineHelpText>
        <label>Last Validation Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promote_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story is marked as ready to be promoted. The user story will appear as &apos;Ahead&apos; and available to be selected in the Branch Management and Promotion pages.</description>
        <inlineHelpText>If checked, the User Story is marked as ready to be promoted. The user story will appear as &apos;Ahead&apos; and available to be selected in the Promotion and Branch Management pages.</inlineHelpText>
        <label>Ready to Promote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promote_and_Deploy__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this checkbox is checked, a promotion and deployment of this User Story will be started.</inlineHelpText>
        <label>Promote and Deploy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promote_as_Single_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promote as Single Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promotion_Test_Level__c</fullName>
        <description>Test Level to apply in the deployment of the User Story.</description>
        <inlineHelpText>Test Level to apply in the deployment of the User Story.</inlineHelpText>
        <label>Promotion Test Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NoTestRun</fullName>
                    <default>true</default>
                    <label>NoTestRun</label>
                </value>
                <value>
                    <fullName>RunSpecifiedTests</fullName>
                </value>
                <value>
                    <fullName>RunLocalTests</fullName>
                </value>
                <value>
                    <fullName>RunAllTestsInOrg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkSubmitService.cls
public with sharing class WorkSubmitService implements CLIInterface {

    private final Settings cSetting = new Settings();
    private final List<String> attNames = new List<String>{
            'MetaData', 'Git MetaData', 'Test Classes'
    };
    private final String orgId = UserInfo.getOrganizationId();
    private final String VALIDATION = 'Validation';
    private final String SLASH = '/';
    private final String NONE = 'none';
    private final String VALIDATE = 'validate';
    private final String PROMOTE = 'promote';
    private final String DEPLOY = 'deploy';
    private User_Story__c userStory;


    /**
    * Empty Constructor
    */
    public WorkSubmitService() {
    }

    /**
     * Get instance of WorkSubmitService that implements CLI Interface
     * @return instance of WorkSubmitService()
     */
    public CLIInterface getInstance() {
        return new WorkSubmitService();
    }

    /**
     * Runs requested operation under root service
     * @return JSON of CliSfDataWrapper.ReturnWrapper as return of requestedAction
     */
    public String run(CliProxy.CLIWrapper record) {
        List<String> checkOlsList = CliSecurityService.checkOLS(new List<String>{
                Schema.SObjectType.User_Story__c.getName()
        });
        if(!checkOlsList.isEmpty()) {
            return JSON.serialize(new CliSfDataWrapper(CliSfDataWrapper.StatusResult.ERROR.name(), Label.Insufficient_Access + checkOlsList));
        }

        String requestedAction = record.operation.toLowerCase();
        SubmitServiceWrapper params = (SubmitServiceWrapper) JSON.deserialize(record.body, SubmitServiceWrapper.class);

        List<User_Story__c> userStoryList = [SELECT Id, Name, Promote_and_Deploy__c, Promote_Change__c, Last_Validation_Promotion__c, Project__c, Release__c, Environment__c, Promote_as_Single_Step__c, Promotion_Test_Level__c, Org_Credential__c FROM User_Story__c WHERE Id = :params.usId LIMIT 1];
        if(userStoryList.isEmpty()) {
            // This case of no user story found is handled by CLI client
            return JSON.serialize(new CliSfDataWrapper(CliSfDataWrapper.StatusResult.OK.name(), null));
        }
        userStory = userStoryList[0];

        return (requestedAction == VALIDATE ? validate() : requestedAction == PROMOTE || requestedAction == DEPLOY ? promoteDeploy(requestedAction) : Label.UnSupportedOperation);
    }

    /**
     * Changes "promote" or "promote and deploy" USer Story checkboxes
     * @param action  promote to change "promote" checkbox or deploy to change "promote and deploy" checkbox
     * @return JSON of CliSfDataWrapper.ReturnWrapper
     */
    public String promoteDeploy(String action) {
        List<String> fieldList = new List<String>();
        WorkSubmitDataWrapper returnDataWrapper = new WorkSubmitDataWrapper();
        if(action == PROMOTE) {
            userStory.Promote_Change__c = true;
            fieldList.add(Schema.SObjectType.User_Story__c.fields.Promote_Change__c.getName());
        } else if(action == DEPLOY) {
            userStory.Promote_and_Deploy__c = true;
            fieldList.add(Schema.SObjectType.User_Story__c.fields.Promote_and_Deploy__c.getName());
        }
        List<String> checkFlsList = CliSecurityService.checkFLS(Schema.SObjectType.User_Story__c.getName(), fieldList, Utilities.DML_Action.UPD);
        if(!checkFlsList.isEmpty()) {
            returnDataWrapper.status = CliSfDataWrapper.StatusResult.ERROR.name();
            returnDataWrapper.message = Label.Insufficient_Access + checkFlsList;
            return(JSON.serialize(returnDataWrapper));
        }
        try {
            Utilities.Secure_DML(userStory, Utilities.DML_Action.UPD, schema.SObjectType.User_Story__c);
            returnDataWrapper.status = CliSfDataWrapper.StatusResult.OK.name();
            returnDataWrapper.userStory = userStory;
        } catch(Exception excp) {
            returnDataWrapper.status = CliSfDataWrapper.StatusResult.ERROR.name();
            returnDataWrapper.message = excp.getMessage();
        }
        return(JSON.serialize(returnDataWrapper));
    }

    /**
     * This method creates a validation deployment for defined usId
     * @param usId - user Story Id to validate
     * @return JSON of CliSfDataWrapper.ReturnWrapper
     */
    private String validate() {
        List<String> checkFlsList = new List<String>();
        List<String> checkFlsPromotion = CliSecurityService.checkFLS(Schema.SObjectType.Promotion__c.getName(), new List<String>{
                Schema.SObjectType.Promotion__c.fields.Project__c.getName(), Schema.SObjectType.Promotion__c.fields.Release__c.getName(), Schema.SObjectType.Promotion__c.fields.Source_Org_Credential__c.getName(), Schema.SObjectType.Promotion__c.fields.Source_Environment__c.getName(), Schema.SObjectType.Promotion__c.fields.Send_Deployment_Complete_email__c.getName(), Schema.SObjectType.Promotion__c.fields.Status__c.getName()
        }, Utilities.DML_Action.INS);
        if(!checkFlsPromotion.isEmpty()) {
            checkFlsList.addAll(checkFlsPromotion);
        }
        List<String> checkFlsPromotedUserStory = CliSecurityService.checkFLS(Schema.SObjectType.Promoted_User_Story__c.getName(), new List<String>{
                Schema.SObjectType.Promoted_User_Story__c.fields.User_Story__c.getName(), Schema.SObjectType.Promoted_User_Story__c.fields.Promotion__c.getName()
        }, Utilities.DML_Action.INS);
        if(!checkFlsPromotedUserStory.isEmpty()) {
            checkFlsList.addAll(checkFlsPromotedUserStory);
        }
        List<String> checkFlsUserStory = CliSecurityService.checkFLS(Schema.SObjectType.User_Story__c.getName(), new List<String>{
                Schema.SObjectType.User_Story__c.fields.Last_Validation_Promotion__c.getName(), Schema.SObjectType.User_Story__c.fields.Last_Validation_Deployment__c.getName()
        }, Utilities.DML_Action.UPD);
        if(!checkFlsPromotedUserStory.isEmpty()) {
            checkFlsList.addAll(checkFlsPromotedUserStory);
        }

        if(!checkFlsList.isEmpty()) {
            return JSON.serialize(new CliSfDataWrapper(CliSfDataWrapper.StatusResult.ERROR.name(), Label.Insufficient_Access + checkFlsList));
        }

        Promotion__c promotion = new Promotion__c();
        promotion.Project__c = userStory.Project__c;
        promotion.Release__c = userStory.Release__c;
        promotion.Source_Org_Credential__c = userStory.Org_Credential__c;
        promotion.Source_Environment__c = userStory.Environment__c;
        promotion.Send_Deployment_Complete_email__c = true;
        promotion.Status__c = VALIDATION;
        Utilities.Secure_DML(promotion, Utilities.DML_Action.INS, schema.SObjectType.Promotion__c);

        Promoted_User_Story__c pus = new Promoted_User_Story__c(User_Story__c = userStory.Id, Promotion__c = promotion.Id);
        pus.Name = 'Promoted User Story: ' + userStory.Name;
        Utilities.Secure_DML(pus, Utilities.DML_Action.INS, schema.SObjectType.Promoted_User_Story__c);

        userStory.Last_Validation_Promotion__c = promotion.Id;
        userStory.Last_Validation_Deployment__c = null;
        Utilities.Secure_DML(userStory, Utilities.DML_Action.UPD, schema.SObjectType.User_Story__c);

        DeployAPI.deployPromotionAsync(userStory.Last_Validation_Promotion__c, userStory.Name, true, userStory.Promote_as_Single_Step__c, userStory.Promotion_Test_Level__c);
        return JSON.serialize(new WorkSubmitDataWrapper(CliSfDataWrapper.StatusResult.OK.name(), 'Promotion record ' + promotion.Id + ' has been created for User Story ' + userStory.Id));
    }

    /**
     * Wrapper class to deserialize copado:work:submit api call Body
     */
    @TestVisible
    private class SubmitServiceWrapper {
        public String usId;
    }

    @TestVisible
    private class WorkSubmitDataWrapper extends CliSfDataWrapper {
        public User_Story__c userStory;
        public WorkSubmitDataWrapper() {
        }
        public WorkSubmitDataWrapper(String stat, User_Story__c us) {
            status = stat;
            userStory = us;
        }
        public WorkSubmitDataWrapper(String stat, String msg) {
            status = stat;
            message = msg;
        }
    }
}