objects/Promoted_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Promotions</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoryTriggerHandler.cls
public without sharing class UserStoryTriggerHandler implements ITrigger {
    public UserStoryTriggerHandler() {
    }

    public void bulkBefore() {
        UserStoryTriggerHelper.prepareMaps();
    }

    public void bulkAfter() {
    }

    /**
        Modifier is set to private after checking that it was not being referenced anywhere else,
        so that way the scope of the method funcionality can be reduced and more clear
    */
    private void beforeCommon(SObject oldSo, SObject so) {
        UserStoryTriggerHelper.setProject((User_Story__c) so);
        UserStoryTriggerHelper.setEnvironment((User_Story__c) so);
        UserStoryTriggerHelper.validateOrgEnvironmentRelationship((User_Story__c) so);
        UserStoryTriggerHelper.checkSprints((User_Story__c) oldSo, (User_Story__c) so);
        UserStoryTriggerHelper.setOrderBeforeUpdate((User_Story__c) oldSo, (User_Story__c) so);
    }

    public void beforeInsert(SObject so) {
        beforeCommon(null, so);
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        beforeCommon(oldSo, so);
        UserStoryTriggerHelper.setChildPromotedUserStoriesAsOutdated((User_Story__c) oldSo, (User_Story__c) so);
    }
    public void beforeDelete(SObject so) {
    }

    public void afterInsert(SObject so) {
    }

    public void afterUpdate(SObject oldSo, SObject so) {
        UserStoryTriggerHelper.addUserStoryToPromoteDeployQueue((User_Story__c) oldSo, (User_Story__c) so);
        UserStoryTriggerHelper.stopIndexingMetadata((User_Story__c) oldSo, (User_Story__c) so);
    }

    public void afterDelete(SObject so) {
    }

    public void afterUndelete(SObject so) {
    }
    public void andFinally() {
        UserStoryTriggerHelper.promoteAndDeployUserStories();
        UserStoryTriggerHelper.updateUserStories();
        update new List<Promoted_User_Story__c>(UserStoryTriggerHelper.promotedUserStoriesToUpdateAsOutdated);
    }
}