objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sprint where the User Story is planned.</description>
        <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkDisplayService.cls
public with sharing class WorkDisplayService implements CLIInterface {
    /**
     * Empty Constructor
     */
    public WorkDisplayService() {
    }
    /**
     * Get instance of WorkDisplayService that implements CLI Interface
     * @return instance of WorkDisplayService()
     */
    public CLIInterface getInstance() {
        return new WorkDisplayService();
    }

    /**
     * Runs requested operation under root service
     * @return JSON of CliSfDataWrapper.ReturnWrapper
     */
    public String run(CliProxy.CLIWrapper record) {
        List<String> checkOlsList = CliSecurityService.checkOLS(new List<String>{ Schema.SObjectType.User_Story__c.getName() });
        if (!checkOlsList.isEmpty()) {
            return JSON.serialize(new CliSfDataWrapper(CliSfDataWrapper.StatusResult.ERROR.name(), Label.Insufficient_Access + checkOlsList));
        }
        WorkDisplayWrapper params = (WorkDisplayWrapper) JSON.deserialize(record.body, WorkDisplayWrapper.class);
        // Passing directly params.value to que string query doesen't work.
        String prmVal = params.value;

        String soqlString = 'SELECT Id, Name, User_Story_Title__c, Status__c, Project__r.Name, Sprint__c, Release__r.Name FROM User_Story__c WHERE {0} = :prmVal LIMIT 1';
        String dynamicQuery = String.format(soqlString, new List<String>{ String.escapeSingleQuotes(params.criteria) });
        List<User_Story__c> sobjList = Database.query(dynamicQuery);
        return (JSON.serialize(new WorkDisplayDataWrapper(CliSfDataWrapper.StatusResult.OK.name(), !sobjList.isEmpty() ? sobjList[0] : null)));
    }
    /**
     * Wrapper class to deserialize copado:work:display api call Body
     */
    @TestVisible
    private class WorkDisplayWrapper {
        public String criteria;
        public String value;
    }

    @TestVisible
    private class WorkDisplayDataWrapper extends CliSfDataWrapper {
        public User_Story__c userStory;
        public WorkDisplayDataWrapper(String stat, User_Story__c us) {
            status = stat;
            userStory = us;
        }
    }
}